# Generated by Django 4.0.3 on 2022-12-23 14:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio'),
        ),
    ]
