# Generated by Django 4.0.3 on 2022-12-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0002_alter_song_image_alter_song_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song',
        ),
    ]
