# Generated by Django 4.0.3 on 2022-12-23 16:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0003_remove_song_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='audio'),
        ),
    ]
