# Generated by Django 4.0.3 on 2022-12-24 04:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadApp', '0004_song_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image1',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
    ]
